// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartbuildingwater.proto

package grpc.examples.smartbuildingwater;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartbuildingwater.HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
